# Conexión usando las variables que pusiste en Render
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# CRUCIAL PARA DOCKER EN RENDER:
# Render le asigna a tu contenedor un puerto dinámico mediante la variable PORT.
# Esta línea le dice a Spring Boot que escuche EN ESE PUERTO en producción.
server.port=${PORT:8080}